### ISSUE TITLE
你好，我这边有几个站无法进行添加

### ISSUE THREAD

**Issue by ShmilyTMD** [hsuyelin/nas-tools-sites#13]
飞天拉面提示未找到用户名输入框
EXO也是提示未找到用户名输入框

**Comment by iovejieba** [comment]
> 飞天拉面提示未找到用户名输入框 EXO也是提示未找到用户名输入框

exo 我改完的那个我测是可以了 你可以拉下 自己生成替换下看看

**Comment by ShmilyTMD** [comment]
> > 飞天拉面提示未找到用户名输入框 EXO也是提示未找到用户名输入框
> 
> exo 我改完的那个我测是可以了 你可以拉下 自己生成替换下看看

exo可以了，谢谢
