### ISSUE TITLE
部分大型站点失效

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools-sites#25]
Bug：

猫站站点资源无法打开（打开后为空白）且资源搜索时无法搜索到该站点的资源。
不可说站点站点资源打开后无法识别免费的种子。

https://github.com/hsuyelin/nas-tools/issues/397

**Comment by jackloves111** [comment]
不过猫好像是加了CF盾导致的

**Comment by jackloves111** [comment]
@iovejieba @Teddy-Zhu 能不能解包MP的不可说站点的json，我加上去试试，MP好像正常的。MP的包我解不来

**Comment by iovejieba** [comment]
> @iovejieba @Teddy-Zhu 能不能解包MP的不可说站点的json，我加上去试试，MP好像正常的。MP的包我解不来

mp的我也没解明白  等大佬看看给个加密解密吧  我看有说kamept的问题的 我去看了下归总的sites 咱们这边好像一直没加kamept  不知道他们说之前正常 是个怎么正常

**Comment by jackloves111** [comment]
这个站我也没有，没试过

**Comment by jackloves111** [comment]
今天去搞了一下mp，上手难度有点大的，nt都整不明白的人，mp估计无望了。nt这边大佬好久没维护了

**Comment by jackloves111** [comment]
不过mp缺失实现了憨憨刷流，我试了是可以的

**Comment by iovejieba** [comment]
> 不过mp缺失实现了憨憨刷流，我试了是可以的

hh不好说 没号 可能mp那边项目给它做了特殊的siteconfig 为了兼容它  也不排除吧   不好说 我记得大佬说过好像憨憨的rss比较独特

**Comment by jackloves111** [comment]
> > 不过mp缺失实现了憨憨刷流，我试了是可以的
> 
> hh不好说 没号 可能mp那边项目给它做了特殊的siteconfig 为了兼容它 也不排除吧 不好说 我记得大佬说过好像憨憨的rss比较独特

又可能，为了这个站点单独做兼容，毕竟憨憨也算是比较大的站点了，现在猫站开了CF盾，目前基本都用不了了

**Comment by iovejieba** [comment]
> > > 不过mp缺失实现了憨憨刷流，我试了是可以的
> > 
> > 
> > hh不好说 没号 可能mp那边项目给它做了特殊的siteconfig 为了兼容它 也不排除吧 不好说 我记得大佬说过好像憨憨的rss比较独特
> 
> 又可能，为了这个站点单独做兼容，毕竟憨憨也算是比较大的站点了，现在猫站开了CF盾，目前基本都用不了了

猫cf的话 不行先挂外部索引 跑个镜像过盾

**Comment by Teddy-Zhu** [comment]
mp 改了加密方式不太清楚,怕是难猜了加密模块cpython 编译起来了,硬分析难搞

**Comment by jackloves111** [comment]
该问题已经解决，故关闭

https://github.com/hsuyelin/nas-tools-sites/commit/3d23411d4cc3230fe4fd68006281f4f2524d041b
