### ISSUE TITLE
这个老哥改了没测试吗？按照新的程序打包的站点文件导致程序无法运行了

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools-sites#30]
![image](https://github.com/hsuyelin/nas-tools-sites/assets/89971817/05ddf874-102a-424d-a010-06b966a8a39d)

![image](https://github.com/hsuyelin/nas-tools-sites/assets/89971817/b7e2feef-9cbd-4390-806d-9944a783fbfc)

建议大佬回退一下版本！@hsuyelin  

他好像是把别人那个打包的版本的写进去了

**Comment by hsuyelin** [comment]
已修复
